//! Heuristic-based generation of memory item candidates from scan results.
//!
//! Produces 3-5 structured candidates that a human can confirm, reject, or reformulate.
//! Rules are binary and traceable — no opaque scoring.

use std::collections::HashSet;
use std::path::Path;
use std::sync::LazyLock;

use anyhow::{Context, Result};
use regex::Regex;

use super::scan::DomainInfo;

// ── Regex patterns for candidate detection ─────────────────────────

/// Patterns in file paths or function names suggesting an exception.
static RE_EXCEPTION_NAMING: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(legacy|compat|override|workaround|migration|deprecated|old_|_old|_v1\b|v1_)")
        .unwrap()
});

/// Patterns in comments suggesting a deliberate decision.
static RE_DECISION_COMMENT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(decision|chosen|we\s+decided|deliberately|intentionally|on\s+purpose|trade-?off|ADR)",
    )
    .unwrap()
});

/// Patterns for util/helper files to exclude.
static RE_UTILS_PATH: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(utils?|helpers?|constants?|config|setup|index)\.(ts|js|py|rs|go)$").unwrap()
});

// ── Types ──────────────────────────────────────────────────────────

/// A memory item candidate generated by heuristics.
#[derive(Debug, Clone)]
pub struct Candidate {
    /// Candidate ID (e.g. "billing-001").
    pub id: String,
    /// Target domain.
    pub domain: String,
    /// Proposed type.
    pub type_: CandidateType,
    /// Proposed text describing the candidate.
    pub text: String,
    /// Human-readable rationale for why this was proposed.
    pub rationale: String,
    /// Files and tests that support this candidate.
    pub provenance: Vec<ProvenanceEntry>,
    /// Target note path.
    pub target_note: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CandidateType {
    Exception,
    Decision,
    BusinessRule,
}

impl std::fmt::Display for CandidateType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CandidateType::Exception => write!(f, "exception"),
            CandidateType::Decision => write!(f, "decision"),
            CandidateType::BusinessRule => write!(f, "business_rule"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ProvenanceEntry {
    pub kind: String, // "file", "test", "comment"
    pub ref_: String,
}

// ── Constants ──────────────────────────────────────────────────────

const MAX_CANDIDATES: usize = 5;
const MIN_FILE_LINES: usize = 50;

// ── Core generation logic ──────────────────────────────────────────

/// Generate memory item candidates from scan results.
pub fn generate(domains: &[DomainInfo]) -> Vec<Candidate> {
    let mut all_candidates: Vec<Candidate> = Vec::new();

    for domain in domains {
        let mut domain_candidates = Vec::new();

        // Heuristic 1: exception candidates from file naming
        detect_exception_candidates(domain, &mut domain_candidates);

        // Heuristic 2: decision candidates from comments
        detect_decision_candidates(domain, &mut domain_candidates);

        // Heuristic 3: business_rule candidates from test + comment combinations
        detect_business_rule_candidates(domain, &mut domain_candidates);

        all_candidates.extend(domain_candidates);
    }

    // Deduplicate: one candidate per (file, type) pair
    deduplicate(&mut all_candidates);

    // Prioritize and limit
    prioritize_and_limit(&mut all_candidates);

    // Assign sequential IDs
    assign_ids(&mut all_candidates);

    all_candidates
}

// ── Heuristic: exception detection ─────────────────────────────────

fn detect_exception_candidates(domain: &DomainInfo, candidates: &mut Vec<Candidate>) {
    for file in &domain.files {
        if is_excluded_path(file) {
            continue;
        }

        if RE_EXCEPTION_NAMING.is_match(file) {
            // Check the file has some substance
            let line_count = count_file_lines(file);
            if line_count < MIN_FILE_LINES {
                continue;
            }

            let filename = std::path::Path::new(file)
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default();

            let mut provenance = vec![ProvenanceEntry {
                kind: "file".to_string(),
                ref_: file.clone(),
            }];

            // Check for associated test
            if let Some(test_file) = find_test_for_file(file, &domain.test_files) {
                provenance.push(ProvenanceEntry {
                    kind: "test".to_string(),
                    ref_: test_file,
                });
            }

            candidates.push(Candidate {
                id: String::new(), // assigned later
                domain: domain.name.clone(),
                type_: CandidateType::Exception,
                text: format!(
                    "{} seems to contain a special case or legacy behavior",
                    filename
                ),
                rationale: format!(
                    "File path '{}' contains exception naming pattern (legacy/compat/override)",
                    file
                ),
                provenance,
                target_note: format!(".wiki/domains/{}/_overview.md", domain.name),
            });
        }
    }
}

// ── Heuristic: decision detection ──────────────────────────────────

fn detect_decision_candidates(domain: &DomainInfo, candidates: &mut Vec<Candidate>) {
    for comment in &domain.comments {
        // Comments are in format "[TAG] text"
        let text = comment
            .strip_prefix("[TODO] ")
            .or_else(|| comment.strip_prefix("[FIXME] "))
            .or_else(|| comment.strip_prefix("[HACK] "))
            .or_else(|| comment.strip_prefix("[NOTE] "))
            .unwrap_or(comment);

        if RE_DECISION_COMMENT.is_match(text) && !is_generic_text(text) {
            candidates.push(Candidate {
                id: String::new(),
                domain: domain.name.clone(),
                type_: CandidateType::Decision,
                text: truncate_text(text, 120),
                rationale: "Comment contains decision pattern (decided/deliberately/intentionally)"
                    .to_string(),
                provenance: vec![ProvenanceEntry {
                    kind: "comment".to_string(),
                    ref_: comment.clone(),
                }],
                target_note: format!(".wiki/domains/{}/_overview.md", domain.name),
            });
        }
    }
}

// ── Heuristic: business_rule detection ─────────────────────────────

fn detect_business_rule_candidates(domain: &DomainInfo, candidates: &mut Vec<Candidate>) {
    // Look for files with tests AND meaningful TODO/HACK/NOTE comments
    let files_with_tests: HashSet<&str> = domain
        .test_files
        .iter()
        .filter_map(|tf| infer_source_for_test(tf))
        .collect();

    for file in &domain.files {
        if is_excluded_path(file) {
            continue;
        }

        let line_count = count_file_lines(file);
        if line_count < MIN_FILE_LINES {
            continue;
        }

        // Check if this file has an associated test
        let file_base = std::path::Path::new(file)
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_default();

        let has_test = files_with_tests.iter().any(|src| src.contains(&file_base));

        if !has_test {
            continue;
        }

        // Look for relevant comments in this domain for this file
        let relevant_comments: Vec<&String> = domain
            .comments
            .iter()
            .filter(|c| {
                let text = c.split("] ").nth(1).unwrap_or(c);
                !RE_DECISION_COMMENT.is_match(text) && !is_generic_text(text)
            })
            .collect();

        if relevant_comments.is_empty() {
            continue;
        }

        let first_comment = relevant_comments[0];
        let comment_text = first_comment.split("] ").nth(1).unwrap_or(first_comment);

        let mut provenance = vec![ProvenanceEntry {
            kind: "file".to_string(),
            ref_: file.clone(),
        }];

        if let Some(test_file) = find_test_for_file(file, &domain.test_files) {
            provenance.push(ProvenanceEntry {
                kind: "test".to_string(),
                ref_: test_file,
            });
        }

        provenance.push(ProvenanceEntry {
            kind: "comment".to_string(),
            ref_: first_comment.clone(),
        });

        candidates.push(Candidate {
            id: String::new(),
            domain: domain.name.clone(),
            type_: CandidateType::BusinessRule,
            text: truncate_text(comment_text, 120),
            rationale: format!(
                "File '{}' has tests and contains a TODO/HACK/NOTE comment",
                file
            ),
            provenance,
            target_note: format!(".wiki/domains/{}/_overview.md", domain.name),
        });
    }
}

// ── Helpers ────────────────────────────────────────────────────────

fn is_excluded_path(path: &str) -> bool {
    // Exclude test-only files
    if path.contains("/test/")
        || path.contains("/tests/")
        || path.contains("/__tests__/")
        || path.contains(".test.")
        || path.contains(".spec.")
        || path.contains("_test.")
    {
        return true;
    }

    // Exclude utility files
    RE_UTILS_PATH.is_match(path)
}

fn is_generic_text(text: &str) -> bool {
    let generic_patterns = [
        "this module",
        "this file",
        "this class",
        "this function",
        "this service",
        "handles",
        "manages",
        "processes",
        "implements",
    ];
    let lower = text.to_lowercase();
    // Too short to be meaningful
    if text.len() < 15 {
        return true;
    }
    generic_patterns
        .iter()
        .any(|p| lower.starts_with(p) && lower.len() < 60)
}

fn count_file_lines(path: &str) -> usize {
    std::fs::read_to_string(path)
        .map(|c| c.lines().count())
        .unwrap_or(0)
}

fn find_test_for_file(source_file: &str, test_files: &[String]) -> Option<String> {
    let stem = std::path::Path::new(source_file)
        .file_stem()
        .map(|s| s.to_string_lossy().to_string())?;

    test_files.iter().find(|tf| tf.contains(&stem)).cloned()
}

fn infer_source_for_test(test_file: &str) -> Option<&str> {
    let stem = std::path::Path::new(test_file).file_stem()?;
    let name = stem.to_str()?;
    // Strip common test suffixes: file.test.ts -> file, file_test.rs -> file
    let base = name
        .strip_suffix(".test")
        .or_else(|| name.strip_suffix(".spec"))
        .or_else(|| name.strip_suffix("_test"))
        .unwrap_or(name);
    Some(base)
}

fn truncate_text(text: &str, max_len: usize) -> String {
    if text.len() <= max_len {
        text.to_string()
    } else {
        format!("{}...", &text[..max_len - 3])
    }
}

fn type_priority(t: &CandidateType) -> u8 {
    match t {
        CandidateType::Exception => 0,
        CandidateType::Decision => 1,
        CandidateType::BusinessRule => 2,
    }
}

fn deduplicate(candidates: &mut Vec<Candidate>) {
    let mut seen: HashSet<(String, String)> = HashSet::new(); // (main_file, type)
    candidates.retain(|c| {
        let main_file = c
            .provenance
            .first()
            .map(|p| p.ref_.clone())
            .unwrap_or_default();
        let key = (main_file, c.type_.to_string());
        seen.insert(key)
    });
}

fn prioritize_and_limit(candidates: &mut Vec<Candidate>) {
    // Sort: exception > decision > business_rule, then by provenance richness
    candidates.sort_by(|a, b| {
        let type_cmp = type_priority(&a.type_).cmp(&type_priority(&b.type_));
        if type_cmp != std::cmp::Ordering::Equal {
            return type_cmp;
        }
        b.provenance.len().cmp(&a.provenance.len())
    });

    candidates.truncate(MAX_CANDIDATES);
}

fn assign_ids(candidates: &mut [Candidate]) {
    let mut domain_counters: std::collections::HashMap<String, u32> =
        std::collections::HashMap::new();

    for c in candidates.iter_mut() {
        let counter = domain_counters.entry(c.domain.clone()).or_insert(0);
        *counter += 1;
        c.id = format!("{}-{:03}", c.domain, counter);
    }
}

// ── File generation (task 015) ─────────────────────────────────────

/// Format candidates into a markdown file.
pub fn format_candidates_markdown(candidates: &[Candidate]) -> String {
    let mut lines = vec![
        "# Memory Candidates".to_string(),
        String::new(),
        "> Auto-generated proposals to confirm, reject, or reformulate.".to_string(),
        "> These candidates are not yet confirmed memory.".to_string(),
        "> Edit this file or use `project-wiki promote <id>` to validate.".to_string(),
    ];

    if candidates.is_empty() {
        lines.push(String::new());
        lines.push("No candidates detected.".to_string());
        return lines.join("\n");
    }

    // Group by domain
    let mut current_domain = String::new();

    for c in candidates {
        if c.domain != current_domain {
            lines.push(String::new());
            lines.push(format!("## {}", c.domain));
            current_domain = c.domain.clone();
        }

        lines.push(String::new());
        lines.push(format!("### {}", c.id));
        lines.push(String::new());
        lines.push("- **status**: pending".to_string());
        lines.push(format!("- **type**: {}", c.type_));
        lines.push("- **confidence**: inferred".to_string());
        lines.push("- **provenance**:".to_string());
        for p in &c.provenance {
            lines.push(format!("  - {}: {}", p.kind, p.ref_));
        }
        lines.push(format!("- **rationale**: {}", c.rationale));
        lines.push(format!("- **target**: {}", c.target_note));
        lines.push(String::new());
        lines.push(format!("> {}", c.text));
        lines.push(String::new());
        lines.push("**Action** : `confirm` | `reformulate` | `reject`".to_string());
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Write the _candidates.md file to disk.
/// If the file already exists, preserves candidates that have been processed (non-pending).
pub fn write_candidates_file(wiki_dir: &Path, candidates: &[Candidate]) -> Result<()> {
    let path = wiki_dir.join("_candidates.md");

    if candidates.is_empty() {
        // Don't create file if no candidates
        return Ok(());
    }

    // Check for existing processed candidates
    let existing_processed = if path.exists() {
        parse_processed_ids(&path)?
    } else {
        HashSet::new()
    };

    // Filter out candidates whose IDs clash with already-processed ones
    let new_candidates: Vec<&Candidate> = candidates
        .iter()
        .filter(|c| !existing_processed.contains(&c.id))
        .collect();

    if new_candidates.is_empty() && !existing_processed.is_empty() {
        // All candidates already processed, don't overwrite
        return Ok(());
    }

    // Generate the full file with new candidates
    let owned: Vec<Candidate> = new_candidates.into_iter().cloned().collect();
    let content = format_candidates_markdown(&owned);
    std::fs::write(&path, &content)
        .with_context(|| format!("Failed to write {}", path.display()))?;

    Ok(())
}

/// Parse existing _candidates.md to find IDs that have been confirmed or rejected.
fn parse_processed_ids(path: &Path) -> Result<HashSet<String>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to read {}", path.display()))?;

    let mut ids = HashSet::new();
    let mut current_id = String::new();

    for line in content.lines() {
        if let Some(id) = line.strip_prefix("### ") {
            current_id = id.trim().to_string();
        }
        if line.contains("**status**:") && !current_id.is_empty() {
            let status = line.split("**status**:").nth(1).unwrap_or("").trim();
            if status != "pending" {
                ids.insert(current_id.clone());
            }
        }
    }

    Ok(ids)
}

// ── Tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_domain(
        name: &str,
        files: Vec<&str>,
        comments: Vec<&str>,
        test_files: Vec<&str>,
    ) -> DomainInfo {
        DomainInfo {
            name: name.to_string(),
            files: files.into_iter().map(|s| s.to_string()).collect(),
            dependencies: Vec::new(),
            models: Vec::new(),
            routes: Vec::new(),
            comments: comments.into_iter().map(|s| s.to_string()).collect(),
            test_files: test_files.into_iter().map(|s| s.to_string()).collect(),
        }
    }

    #[test]
    fn test_heuristic_exception_legacy_naming() {
        // Create a temp file with enough lines
        let dir = tempfile::TempDir::new().unwrap();
        let file_path = dir.path().join("legacy_pricing.ts");
        let content = "line\n".repeat(60);
        std::fs::write(&file_path, &content).unwrap();

        let domain = make_domain("billing", vec![file_path.to_str().unwrap()], vec![], vec![]);

        let mut candidates = Vec::new();
        detect_exception_candidates(&domain, &mut candidates);

        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0].type_, CandidateType::Exception);
        assert!(candidates[0].text.contains("legacy_pricing"));
    }

    #[test]
    fn test_heuristic_exception_compat_naming() {
        let dir = tempfile::TempDir::new().unwrap();
        let file_path = dir.path().join("compat_handler.ts");
        let content = "line\n".repeat(60);
        std::fs::write(&file_path, &content).unwrap();

        let domain = make_domain("auth", vec![file_path.to_str().unwrap()], vec![], vec![]);

        let mut candidates = Vec::new();
        detect_exception_candidates(&domain, &mut candidates);

        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0].type_, CandidateType::Exception);
    }

    #[test]
    fn test_heuristic_decision_comment_pattern() {
        let domain = make_domain(
            "billing",
            vec![],
            vec!["[NOTE] We decided to not deduplicate imported rows"],
            vec![],
        );

        let mut candidates = Vec::new();
        detect_decision_candidates(&domain, &mut candidates);

        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0].type_, CandidateType::Decision);
        assert!(candidates[0].text.contains("not deduplicate imported rows"));
    }

    #[test]
    fn test_heuristic_business_rule_test_plus_todo() {
        let dir = tempfile::TempDir::new().unwrap();
        let source = dir.path().join("invoice.ts");
        let content = "line\n".repeat(60);
        std::fs::write(&source, &content).unwrap();

        let test_file = dir.path().join("invoice.test.ts");
        std::fs::write(&test_file, "test content").unwrap();

        let domain = make_domain(
            "billing",
            vec![source.to_str().unwrap()],
            vec!["[TODO] Invoice is only emitted after full sync completes"],
            vec![test_file.to_str().unwrap()],
        );

        let mut candidates = Vec::new();
        detect_business_rule_candidates(&domain, &mut candidates);

        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0].type_, CandidateType::BusinessRule);
    }

    #[test]
    fn test_heuristic_max_5_candidates() {
        let dir = tempfile::TempDir::new().unwrap();
        let content = "line\n".repeat(60);

        let mut files = Vec::new();
        for i in 0..10 {
            let path = dir.path().join(format!("legacy_{i}.ts"));
            std::fs::write(&path, &content).unwrap();
            files.push(path.to_str().unwrap().to_string());
        }

        let domain = DomainInfo {
            name: "billing".to_string(),
            files,
            dependencies: Vec::new(),
            models: Vec::new(),
            routes: Vec::new(),
            comments: Vec::new(),
            test_files: Vec::new(),
        };

        let result = generate(&[domain]);
        assert!(result.len() <= MAX_CANDIDATES);
    }

    #[test]
    fn test_heuristic_exclusion_utils() {
        let dir = tempfile::TempDir::new().unwrap();
        let utils_path = dir.path().join("utils.ts");
        let content = "line\n".repeat(60);
        std::fs::write(&utils_path, &content).unwrap();

        assert!(is_excluded_path(utils_path.to_str().unwrap()));
    }

    #[test]
    fn test_heuristic_exclusion_test_only() {
        assert!(is_excluded_path("src/billing/__tests__/invoice.test.ts"));
        assert!(is_excluded_path("src/billing/invoice.test.ts"));
        assert!(is_excluded_path("tests/billing/invoice_test.rs"));
    }

    #[test]
    fn test_heuristic_dedup_same_file_same_type() {
        let mut candidates = vec![
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Exception,
                text: "First".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "src/legacy.ts".to_string(),
                }],
                target_note: String::new(),
            },
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Exception,
                text: "Second".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "src/legacy.ts".to_string(),
                }],
                target_note: String::new(),
            },
        ];

        deduplicate(&mut candidates);
        assert_eq!(candidates.len(), 1);
    }

    #[test]
    fn test_heuristic_keep_same_file_different_type() {
        let mut candidates = vec![
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Exception,
                text: "Exception".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "src/legacy.ts".to_string(),
                }],
                target_note: String::new(),
            },
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Decision,
                text: "Decision".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "src/legacy.ts".to_string(),
                }],
                target_note: String::new(),
            },
        ];

        deduplicate(&mut candidates);
        assert_eq!(candidates.len(), 2);
    }

    #[test]
    fn test_heuristic_priority_exception_first() {
        let mut candidates = vec![
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::BusinessRule,
                text: "Rule".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "a.ts".to_string(),
                }],
                target_note: String::new(),
            },
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Exception,
                text: "Exception".to_string(),
                rationale: String::new(),
                provenance: vec![ProvenanceEntry {
                    kind: "file".to_string(),
                    ref_: "b.ts".to_string(),
                }],
                target_note: String::new(),
            },
        ];

        prioritize_and_limit(&mut candidates);
        assert_eq!(candidates[0].type_, CandidateType::Exception);
        assert_eq!(candidates[1].type_, CandidateType::BusinessRule);
    }

    #[test]
    fn test_heuristic_provenance_always_present() {
        let dir = tempfile::TempDir::new().unwrap();
        let file_path = dir.path().join("legacy_handler.ts");
        let content = "line\n".repeat(60);
        std::fs::write(&file_path, &content).unwrap();

        let domain = make_domain(
            "auth",
            vec![file_path.to_str().unwrap()],
            vec!["[NOTE] We decided to keep legacy endpoint for compat"],
            vec![],
        );

        let result = generate(&[domain]);
        for c in &result {
            assert!(
                !c.provenance.is_empty(),
                "Candidate {} should have provenance",
                c.id
            );
        }
    }

    #[test]
    fn test_heuristic_empty_scan_no_candidates() {
        let result = generate(&[]);
        assert!(result.is_empty());
    }

    #[test]
    fn test_assign_ids() {
        let mut candidates = vec![
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Exception,
                text: "A".to_string(),
                rationale: String::new(),
                provenance: vec![],
                target_note: String::new(),
            },
            Candidate {
                id: String::new(),
                domain: "billing".to_string(),
                type_: CandidateType::Decision,
                text: "B".to_string(),
                rationale: String::new(),
                provenance: vec![],
                target_note: String::new(),
            },
            Candidate {
                id: String::new(),
                domain: "auth".to_string(),
                type_: CandidateType::BusinessRule,
                text: "C".to_string(),
                rationale: String::new(),
                provenance: vec![],
                target_note: String::new(),
            },
        ];

        assign_ids(&mut candidates);
        assert_eq!(candidates[0].id, "billing-001");
        assert_eq!(candidates[1].id, "billing-002");
        assert_eq!(candidates[2].id, "auth-001");
    }

    #[test]
    fn test_is_generic_text() {
        assert!(is_generic_text("short"));
        assert!(is_generic_text("This module handles billing"));
        assert!(!is_generic_text(
            "We decided to not deduplicate imported rows because clients have homonyms"
        ));
    }

    #[test]
    fn test_truncate_text() {
        assert_eq!(truncate_text("short", 120), "short");
        let long = "a".repeat(200);
        let result = truncate_text(&long, 50);
        assert_eq!(result.len(), 50);
        assert!(result.ends_with("..."));
    }

    // ── File generation tests (task 015) ──

    fn make_candidate(id: &str, domain: &str, type_: CandidateType, text: &str) -> Candidate {
        Candidate {
            id: id.to_string(),
            domain: domain.to_string(),
            type_,
            text: text.to_string(),
            rationale: "Test rationale".to_string(),
            provenance: vec![ProvenanceEntry {
                kind: "file".to_string(),
                ref_: "src/test.ts".to_string(),
            }],
            target_note: format!(".wiki/domains/{}/_overview.md", domain),
        }
    }

    #[test]
    fn test_generate_candidates_file_format() {
        let candidates = vec![
            make_candidate(
                "billing-001",
                "billing",
                CandidateType::Exception,
                "Legacy pricing",
            ),
            make_candidate(
                "billing-002",
                "billing",
                CandidateType::Decision,
                "No dedup",
            ),
        ];

        let md = format_candidates_markdown(&candidates);
        assert!(md.starts_with("# Memory Candidates"));
        assert!(md.contains("## billing"));
        assert!(md.contains("### billing-001"));
        assert!(md.contains("### billing-002"));
    }

    #[test]
    fn test_generate_candidates_all_fields_present() {
        let candidates = vec![make_candidate(
            "billing-001",
            "billing",
            CandidateType::Exception,
            "E1",
        )];

        let md = format_candidates_markdown(&candidates);
        assert!(md.contains("**status**: pending"));
        assert!(md.contains("**type**: exception"));
        assert!(md.contains("**confidence**: inferred"));
        assert!(md.contains("**provenance**:"));
        assert!(md.contains("file: src/test.ts"));
        assert!(md.contains("**rationale**: Test rationale"));
        assert!(md.contains("**target**:"));
        assert!(md.contains("> E1"));
        assert!(md.contains("**Action**"));
    }

    #[test]
    fn test_generate_candidates_zero_candidates() {
        let md = format_candidates_markdown(&[]);
        assert!(md.contains("No candidates detected."));
    }

    #[test]
    fn test_generate_candidates_status_pending() {
        let candidates = vec![make_candidate(
            "billing-001",
            "billing",
            CandidateType::Exception,
            "E1",
        )];
        let md = format_candidates_markdown(&candidates);
        assert!(md.contains("**status**: pending"));
    }

    #[test]
    fn test_write_candidates_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let wiki_dir = dir.path();

        let candidates = vec![make_candidate(
            "billing-001",
            "billing",
            CandidateType::Exception,
            "E1",
        )];

        write_candidates_file(wiki_dir, &candidates).unwrap();

        let path = wiki_dir.join("_candidates.md");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("billing-001"));
    }

    #[test]
    fn test_write_candidates_empty_no_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let wiki_dir = dir.path();

        write_candidates_file(wiki_dir, &[]).unwrap();

        let path = wiki_dir.join("_candidates.md");
        assert!(!path.exists());
    }

    #[test]
    fn test_write_candidates_idempotent() {
        let dir = tempfile::TempDir::new().unwrap();
        let wiki_dir = dir.path();

        let candidates = vec![make_candidate(
            "billing-001",
            "billing",
            CandidateType::Exception,
            "E1",
        )];

        // Write once
        write_candidates_file(wiki_dir, &candidates).unwrap();

        // Modify the file to mark one as confirmed
        let path = wiki_dir.join("_candidates.md");
        let content = std::fs::read_to_string(&path).unwrap();
        let modified = content.replace("**status**: pending", "**status**: confirmed");
        std::fs::write(&path, &modified).unwrap();

        // Write again — should not overwrite confirmed candidate
        write_candidates_file(wiki_dir, &candidates).unwrap();

        let final_content = std::fs::read_to_string(&path).unwrap();
        // If the candidate was already confirmed, a new file with 0 pending candidates
        // should not overwrite
        assert!(!final_content.contains("billing-001") || final_content.contains("confirmed"));
    }

    #[test]
    fn test_parse_processed_ids() {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("_candidates.md");
        let content = r#"# Memory Candidates

## billing

### billing-001

- **status**: confirmed
- **type**: exception

### billing-002

- **status**: pending
- **type**: decision
"#;
        std::fs::write(&path, content).unwrap();

        let ids = parse_processed_ids(&path).unwrap();
        assert!(ids.contains("billing-001"));
        assert!(!ids.contains("billing-002"));
    }
}
